# Generated by Django 6.1 on 2026-08-25 18:02

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/', verbose_name='Фотография')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Фотография галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sort_order', '-created_at'), 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('-is_main', 'sort_order', 'id'), 'verbose_name': 'Фотография модели', 'verbose_name_plural': 'Фотографии модели'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('sort_order', '-created_at'), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='application',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_winter',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ceiling_insulated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='floor_insulated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_walking_area',
        ),
        migrations.RemoveField(
            model_name='product',
            name='heating_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='installation_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='insulation_thickness',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lattice_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_temperature',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sections_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vapor_barrier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ventilation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='walls_insulated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='waterproofing',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='review',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='review',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='project',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.product', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес доставки и установки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='applications/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf', 'doc', 'docx']), core.models.validate_file_size], verbose_name='Прикреплённый файл'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dimensions',
            field=models.CharField(blank=True, max_length=150, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='application',
            name='material',
            field=models.CharField(blank=True, max_length=250, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='project_type',
            field=models.CharField(choices=[('gazebo', 'Беседка'), ('enclosure', 'Вольер'), ('winter_enclosure', 'Зимний вольер'), ('other', 'Другое')], default='gazebo', max_length=30, verbose_name='Тип проекта'),
        ),
        migrations.AlterField(
            model_name='application',
            name='roof_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тип крыши'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('processing', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('gazebo', 'Беседки'), ('enclosure', 'Вольеры')], max_length=20, verbose_name='Тип продукции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, default='TEMP-ARTICLE', max_length=100, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, max_length=500, verbose_name='Доступные цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=150, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='foundation_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тип фундамента'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_glazing',
            field=models.BooleanField(default=False, verbose_name='Есть остекление'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_grill',
            field=models.BooleanField(default=False, verbose_name='Есть мангальная зона'),
        ),
        migrations.AlterField(
            model_name='product',
            name='insulation_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Утепление'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Доступна для заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Популярное'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('gazebo', 'Беседка'), ('enclosure', 'Вольер')], db_index=True, max_length=20, verbose_name='Тип продукции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.TextField(blank=True, verbose_name='Дополнительные опции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=150, verbose_name='Тип конструкции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_days',
            field=models.PositiveIntegerField(default=10, verbose_name='Срок изготовления, дней'),
        ),
        migrations.AlterField(
            model_name='product',
            name='roofing_material',
            field=models.CharField(blank=True, max_length=200, verbose_name='Кровельный материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('summer', 'Летняя'), ('all_season', 'Всесезонная'), ('winter', 'Зимняя')], default='summer', max_length=20, verbose_name='Сезонность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание фотографии'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approximate_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Примерная стоимость'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_days',
            field=models.PositiveIntegerField(default=10, verbose_name='Срок выполнения, дней'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dimensions',
            field=models.CharField(blank=True, max_length=150, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to='projects/after/%Y/%m/', verbose_name='Фотография после'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_before',
            field=models.ImageField(blank=True, null=True, upload_to='projects/before/%Y/%m/', verbose_name='Фотография до'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='project',
            name='materials',
            field=models.CharField(blank=True, max_length=500, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('gazebo', 'Беседка'), ('winter_gazebo', 'Зимняя беседка'), ('grill_gazebo', 'Беседка с мангалом'), ('enclosure', 'Вольер'), ('winter_enclosure', 'Зимний вольер')], max_length=30, verbose_name='Тип проекта'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Оценка'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(max_length=150, verbose_name='Размеры')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая цена')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('is_default', models.BooleanField(default=False, verbose_name='Основной вариант')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Размер и цена',
                'verbose_name_plural': 'Размеры и цены',
                'ordering': ('sort_order', 'price'),
            },
        ),
    ]
