# Generated by Django 6.1 on 2026-08-26 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='project_name',
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание и пожелания'),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='Не указано', max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='project_type',
            field=models.CharField(choices=[('gazebo', 'Беседка'), ('aviary', 'Вольер'), ('winter_aviary', 'Зимний вольер'), ('canopy', 'Навес'), ('other', 'Индивидуальный проект')], default='other', max_length=30, verbose_name='Тип проекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_applications', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
